# Gush configuration file, any comments will be lost.
repo_adapter: github
issue_tracker: github
repo_org: php-cache
repo_name: void-adapter
issue_project_org: php-cache
issue_project_name: void-adapter
meta-header: "This file is part of php-cache\\void-adapter package.\n\n(c) 2015-2015 Aaron Scherer <aequasi@gmail.com>, Tobias Nyholm <tobias.nyholm@gmai.com> \n\nThis source file is subject to the MIT license that is bundled\nwith this source code in the file LICENSE."
pr_type:
    - feature
    - bugfix
    - refactor
    - tests
    - remove
    - style
    - documentation
    - security
table-pr:
    fixed_tickets: ['Fixed Tickets', '']
